<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CellSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        {
            $cells = [
                ['Akabahizi', 1],
                ['Akabeza', 1],
                ['Gacyamo', 1],
                ['Kigarama', 1],
                ['Kinyange', 1],
                ['Kora', 1],
                ['Nyamweru', 2],
                ['Nzove', 2],
                ['Taba', 2],
                ['Kigali', 3],
                ['Mwendo', 3],
                ['Nyabugogo', 3],
                ['Ruriba', 3],
                ['Rwesero', 3],
                ['Kamuhoza', 4],
                ['Katabaro', 4],
                ['Kimisagara', 4],
                ['Kankuba', 5],
                ['Kavumu', 5],
                ['Mataba', 5],
                ['Ntungamo', 5],
                ['Nyarufunzo', 5],
                ['Nyarurenzi', 5],
                ['Runzenze', 5],
                ['Amahoro', 6],
                ['Kabasengerezi', 6],
                ['Kabeza', 6],
                ['Nyabugogo', 6],
                ['Rugenge', 6],
                ['Tetero', 6],
                ['Ubumwe', 6],
                ['Munanira i', 7],
                ['Munanira ii', 7],
                ['Nyakabanda i', 7],
                ['Nyakabanda ii', 7],
                ['Cyivugiza', 8],
                ['Gasharu', 8],
                ['Mumena', 8],
                ['Rugarama', 8],
                ['Agatare', 9],
                ['Biryogo', 9],
                ['Kiyovu', 9],
                ['Rwampara', 9],
                ['Kabuguru i', 10],
                ['Kabuguru ii', 10],
                ['Rwezamenyo i', 10],
                ['Rwezamenyo ii', 10],
                ['Kinyaga', 11],
                ['Musave', 11],
                ['Mvuzo', 11],
                ['Ngara', 11],
                ['Nkuzuzu', 11],
                ['Nyabikenke', 11],
                ['Nyagasozi', 11],
                ['Karuruma', 12],
                ['Nyamabuye', 12],
                ['Nyamugari', 12],
                ['Gasagara', 13],
                ['Gicaca', 13],
                ['Kibara', 13],
                ['Munini', 13],
                ['Murambi', 13],
                ['Musezero', 14],
                ['Ruhango', 14],
                ['Akamatamu', 15],
                ['Bweramvura', 15],
                ['Kidashya', 15],
                ['Ngiryi', 15],
                ['Agateko', 16],
                ['Buhiza', 16],
                ['Muko', 16],
                ['Nkusi', 16],
                ['Nyabuliba', 16],
                ['Nyakabungo', 16],
                ['Nyamitanga', 16],
                ['Kamatamu', 17],
                ['Kamutwa', 17],
                ['Kibaza', 17],
                ['Kamukina', 18],
                ['Kimihurura', 18],
                ['Rugando', 18],
                ['Bibare', 19],
                ['Kibagabaga', 19],
                ['Nyagatovu', 19],
                ['Gacuriro', 20],
                ['Gasharu', 20],
                ['Kagugu', 20],
                ['Murama', 20],
                ['Bwiza', 21],
                ['Cyaruzinge', 21],
                ['Kibenga', 21],
                ['Masoro', 21],
                ['Mukuyu', 21],
                ['Rudashya', 21],
                ['Butare', 22],
                ['Gasanze', 22],
                ['Gasura', 22],
                ['Gatunga', 22],
                ['Muremure', 22],
                ['Sha', 22],
                ['Shango', 22],
                ['Nyabisindu', 23],
                ['Nyarutarama', 23],
                ['Rukiri i', 23],
                ['Rukiri ii', 23],
                ['Bisenga', 24],
                ['Gasagara', 24],
                ['Kabuga ii', 24],
                ['Kinyana', 24],
                ['Mbandazi', 24],
                ['Nyagahinga', 24],
                ['Ruhanga', 24],
                ['Gasabo', 25],
                ['Indatemwa', 25],
                ['Kabaliza', 25],
                ['Kacyatwa', 25],
                ['Kibenga', 25],
                ['Kigabiro', 25],
                ['Gahanga', 26],
                ['Kagasa', 26],
                ['Karembure', 26],
                ['Murinja', 26],
                ['Nunga', 26],
                ['Rwabutenge', 26],
                ['Gatenga', 27],
                ['Karambo', 27],
                ['Nyanza', 27],
                ['Nyarurama', 27],
                ['Kagunga', 28],
                ['Kanserege', 28],
                ['Kinunga', 28],
                ['Kanserege', 29],
                ['Muyange', 29],
                ['Rukatsa', 29],
                ['Busanza', 30],
                ['Kabeza', 30],
                ['Karama', 30],
                ['Rubirizi', 30],
                ['Gasharu', 31],
                ['Kagina', 31],
                ['Kicukiro', 31],
                ['Ngoma', 31],
                ['Bwerankori', 32],
                ['Karugira', 32],
                ['Kigarama', 32],
                ['Nyarurama', 32],
                ['Rwampara', 32],
                ['Ayabaraya', 33],
                ['Cyimo', 33],
                ['Gako', 33],
                ['Gitaraga', 33],
                ['Mbabe', 33],
                ['Rusheshe', 33],
                ['Gatare', 34],
                ['Niboye', 34],
                ['Nyakabanda', 34],
                ['Kamashashi', 35],
                ['Nonko', 35],
                ['Rwimbogo', 35]
            ];
    
            foreach ($cells as $cell) {
                DB::table('cells')->insert([
                    'name' => $cell[0],
                    'sector_id' => $cell[1],
                ]);
            }
        }
    }
}
